spring:
  profiles:
    active: local-postgresql, dev, jwt

---
# Local PostgreSQL
spring:
  config:
    activate.on-profile: local-postgresql

  datasource:
    url: jdbc:postgresql://localhost/yomojomo
    username: postgres

  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect

jwt:
  claims:
    issuer: $JWT_CLAIMS_ISSUER
  secret-key: $JWT_SECRET_KEY
---
# Dev Defaults
spring:
  config:
    activate.on-profile: dev

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
---
# Check Filters Registered
spring:
  config:
    activate.on-profile: filters-registered

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
