package com.ada.earthvalley.yomojomo.article.entities;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.data.annotation.Id;

import com.ada.earthvalley.yomojomo.config.DynamoDbConfig;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;

import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "Article")
public class Article {

	@Id
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String initialArticleid;
	@DynamoDBAttribute
	private String title;
	@DynamoDBAttribute
	private String author;
	@DynamoDBAttribute
	private String source;
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "created")
	@DynamoDBTypeConverted(converter = DynamoDbConfig.LocalDateTimeConverter.class)
	private LocalDateTime createdAt;
	// TODO: Topic은 RDB에서 관리하고 해당 long타입만 저장하는게 베스트일지 (by Daon - 22.11.06)
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "topidId")
	private Long topicId;
	@DynamoDBAttribute
	private List<Section> sections;

	@DynamoDBDocument
	@NoArgsConstructor
	@Getter
	@Setter
	static public class Section {
		@DynamoDBAttribute
		private Tag tag;
		@DynamoDBAttribute
		private List<Info> infos;

		@DynamoDBTypeConvertedEnum
		public enum Tag {
			HEADER, TITLE, PARAGRAPH, IMAGE
		}

		@Builder
		public Section(Tag tag, List<Info> infos) {
			this.tag = tag;
			this.infos = infos;
		}

		@DynamoDBDocument
		@NoArgsConstructor
		@Getter
		@Setter
		static public class Info {
			@DynamoDBAttribute
			private Long index;
			@DynamoDBAttribute
			private String content;

			@Builder
			public Info(Long index, String content) {
				this.index = index;
				this.content = content;
			}
		}

	}

	@Builder
	public Article(String title, String initialArticleid, String author, String source, LocalDateTime createdAt,
		Long topicId, List<Section> sections) {
		this.title = title;
		this.initialArticleid = initialArticleid;
		this.author = author;
		this.source = source;
		this.createdAt = createdAt;
		this.topicId = topicId;
		this.sections = sections;
	}

}
