name: yomojomo CICD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    # 전송할 파일을 담을 디렉토리 생성
    - name: Make Directory for deliver
      run: mkdir dev-deploy

    # Jar 파일 Copy
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./dev-deploy/
    
    # appspec.yml Copy
    - name: Copy appspec
      run: cp appspec.yml ./dev

    # script file Copy
    - name: Copy shell
      run: cp ./scripts/* ./dev

    # 압축파일 형태로 전달
    - name: Make zip file
      run: zip -r -qq -j ./dev-yomojomo-build.zip ./dev-deploy

    # S3 Bucket으로 copy
    - name: Deliver to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: | 
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./dev-yomojomo-build.zip s3://yomojomo-api-deploy/
        
    # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name yomojomo-api \
        --deployment-group-name yomojomo-deploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=yomojomo-api-deploy,bundleType=zip,key=dev-yomojomo-build.zip \
        --region ap-northeast-2
